### ISSUE TITLE
code environment problem

### ISSUE THREAD

**Issue by xjy2020** [UQ-Neusoft-Health-Data-Science/ActiveEA#1]
The virtual environment in the environment.yml file cannot be migrated, and there are some version conflicts. What is the reason? Mainly it may be a problem with graph-tool.

**Comment by uqbingliu** [comment]
Hi @xjy2020 , thanks for reporting this issue. I agree that the package graph-tool might be the cause of conflicts on some devices. 

I have moved few packages out of the environment.yml file and install them separately. Some minor updates in scripts were done as well.  Please pull the repo again and install your environment by following the instructions in readme.txt.

Cheers
